package data_panel_components;

import javax.swing.filechooser.FileSystemView;

import Controllers.Data_Label_Controller;

public class File_Select_Panel extends javax.swing.JPanel {

	Data_Label_Controller ctrl;
    /**
     * Creates new form File_Select_panel
     */
    public File_Select_Panel(Data_Label_Controller ctrl) {
    	this.ctrl = ctrl;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        // create an object of JFileChooser class 
        jFileChooser = new javax.swing.JFileChooser(FileSystemView.getFileSystemView().getHomeDirectory()); 

        // invoke the showsOpenDialog function to show the save dialog 
        int r = jFileChooser.showOpenDialog(null); 

        // if the user selects a file 
        if (r == jFileChooser.APPROVE_OPTION){ 
            // set the label to the path of the selected file 
            System.out.println(jFileChooser.getSelectedFile().getAbsolutePath()); 
        } 
        // if the user cancelled the operation 
        else
            System.out.println("the user cancelled the operation"); 
        setBackground(new java.awt.Color(24, 24, 24));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jFileChooser, javax.swing.GroupLayout.DEFAULT_SIZE, 650, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jFileChooser, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );
    }// </editor-fold>                        


    // Variables declaration - do not modify                     
    private javax.swing.JFileChooser jFileChooser;
    // End of variables declaration                   
}
