package logan.sybilGUI;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;

import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
*
* @author Owner
*/
public class Data_Label_Panel extends javax.swing.JPanel {

   /**
    * Creates new form Data_Label_Panel
    */
   public Data_Label_Panel() {
	   controller = new Data_Label_Controller();
       initComponents();
   }

   /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
   private void initComponents() {
	   buttons = new ArrayList<JButton>();
       side_panel = new javax.swing.JPanel();

       setBackground(new java.awt.Color(34, 40, 44));
       setLayout(new java.awt.BorderLayout());

       side_panel.setBackground(new java.awt.Color(24, 30, 40));
       side_panel.setPreferredSize(new java.awt.Dimension(200, 700));


       ArrayList<String> names = controller.getColumnNames();
       ArrayList<Character> types = controller.getColumnTypes();
       for(int i = 0; i< names.size(); i++) {
    	   make_button(names.get(i),types.get(i));
       }
       add(side_panel, java.awt.BorderLayout.WEST);
   }// </editor-fold>
   
   private void make_button(String name, char t) {
	   JButton btn = new javax.swing.JButton();
       btn.setBackground(new java.awt.Color(24, 30, 40));
       btn.setForeground(new java.awt.Color(153, 153, 153));
       btn.setPreferredSize(new java.awt.Dimension(150, 30));
       
       if(t == 'T')
    	   btn.setIcon(GUI_Util.getIcon("SYBIL_GUI/icons8_t_20px_2.png",20,20)); // NOI18N
       if(t == 'C')
    	   btn.setIcon(GUI_Util.getIcon("SYBIL_GUI/icons8_c_20px_1.png",20,20)); // NOI18N
       if(t == 'N')
    	   btn.setIcon(GUI_Util.getIcon("SYBIL_GUI/icons8_n_20px_2.png",20,20)); // NOI18N
       
       btn.setText(name);
       
       btn.addActionListener(new ActionListener() {
       	public void actionPerformed(ActionEvent e) {
       		JDialog edit_column = new JDialog();
            edit_column.setSize(400, 300);
            Edit_Column_Panel edit_panel = new Edit_Column_Panel(name,t,controller);
            edit_column.add(edit_panel);
            edit_column.setVisible(true);
            
       	}
       });
       buttons.add(btn);
       side_panel.add(btn);
   }

   // Variables declaration - do not modify                     
   private javax.swing.JPanel side_panel;
   private ArrayList<JButton> buttons;
   private Data_Label_Controller controller;
   public char tt= 'N';
   // End of variables declaration                   
}