package logan.sybilGUI;

/**
*
* @author Owner
*/
public class Data_Handler_Panel extends javax.swing.JPanel {
	private int W;
	private int H;
   /**
    * Creates new form Data_Handler_Panel
    */
   public Data_Handler_Panel(int W,int H) {
	   this.W=W;
	   this.H=H;
       initComponents();
   }

   /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
   private void initComponents() {

       buttonGroup1 = new javax.swing.ButtonGroup();
       top_panel = new javax.swing.JPanel();
       jLabel1 = new javax.swing.JLabel();
       jLabel2 = new javax.swing.JLabel();
       jLabel3 = new javax.swing.JLabel();
       jLabel4 = new javax.swing.JLabel();
       center_panel = new javax.swing.JPanel();
       impute_panel = new javax.swing.JPanel();
       mean_btn = new javax.swing.JRadioButton();
       median_btn = new javax.swing.JRadioButton();
       rand_btn = new javax.swing.JRadioButton();
       model_btn = new javax.swing.JRadioButton();
       remove_btn = new javax.swing.JRadioButton();
       outlier_panel = new javax.swing.JPanel();
       std_btn = new javax.swing.JRadioButton();
       std_spinner = new javax.swing.JSpinner();
       dbscan_btn = new javax.swing.JRadioButton();
       jSlider1 = new javax.swing.JSlider();
       iqr_btn = new javax.swing.JRadioButton();
       iqr_spinner = new javax.swing.JSpinner();
       scale_panel = new javax.swing.JPanel();
       width_btn = new javax.swing.JRadioButton();
       numBins_spinner = new javax.swing.JSpinner();
       jRadioButton12 = new javax.swing.JRadioButton();
       jSpinner4 = new javax.swing.JSpinner();
       jRadioButton14 = new javax.swing.JRadioButton();
       standardize_panel = new javax.swing.JPanel();
       standardize_btn = new javax.swing.JRadioButton();

       setBackground(new java.awt.Color(34, 40, 44));
       setPreferredSize(new java.awt.Dimension(W, H));
       setLayout(new java.awt.BorderLayout());

       top_panel.setBackground(new java.awt.Color(20, 20, 20));
       top_panel.setMinimumSize(new java.awt.Dimension(W, 60));
       top_panel.setPreferredSize(new java.awt.Dimension(W, 70));
       top_panel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 100, 5));

       jLabel1.setFont(new java.awt.Font("Courier New", 0, 24)); // NOI18N
       jLabel1.setForeground(new java.awt.Color(102, 102, 102));
       jLabel1.setText("Impute");
       top_panel.add(jLabel1);

       jLabel2.setFont(new java.awt.Font("Courier New", 0, 24)); // NOI18N
       jLabel2.setForeground(new java.awt.Color(102, 102, 102));
       jLabel2.setText("Outlire");
       top_panel.add(jLabel2);

       jLabel3.setFont(new java.awt.Font("Courier New", 0, 24)); // NOI18N
       jLabel3.setForeground(new java.awt.Color(102, 102, 102));
       jLabel3.setText("Scale");
       top_panel.add(jLabel3);

       jLabel4.setFont(new java.awt.Font("Courier New", 0, 24)); // NOI18N
       jLabel4.setForeground(new java.awt.Color(102, 102, 102));
       jLabel4.setText("Standardize");
       top_panel.add(jLabel4);

       add(top_panel, java.awt.BorderLayout.NORTH);

       center_panel.setBackground(new java.awt.Color(34, 40, 44));
       center_panel.setPreferredSize(new java.awt.Dimension(W, H-60));

       impute_panel.setBackground(new java.awt.Color(34, 40, 44));
       impute_panel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
       impute_panel.setPreferredSize(new java.awt.Dimension(210, 600));

       mean_btn.setBackground(new java.awt.Color(34, 40, 44));
       buttonGroup1.add(mean_btn);
       mean_btn.setForeground(new java.awt.Color(153, 153, 153));
       mean_btn.setText("Mean/Most Frequent");
       impute_panel.add(mean_btn);

       median_btn.setBackground(new java.awt.Color(34, 40, 44));
       buttonGroup1.add(median_btn);
       median_btn.setForeground(new java.awt.Color(153, 153, 153));
       median_btn.setText("Median");
       impute_panel.add(median_btn);

       rand_btn.setBackground(new java.awt.Color(34, 40, 44));
       buttonGroup1.add(rand_btn);
       rand_btn.setForeground(new java.awt.Color(153, 153, 153));
       rand_btn.setText("Random");
       impute_panel.add(rand_btn);

       model_btn.setBackground(new java.awt.Color(34, 40, 44));
       buttonGroup1.add(model_btn);
       model_btn.setForeground(new java.awt.Color(153, 153, 153));
       model_btn.setText("Model Based");
       impute_panel.add(model_btn);

       remove_btn.setBackground(new java.awt.Color(34, 40, 44));
       buttonGroup1.add(remove_btn);
       remove_btn.setForeground(new java.awt.Color(153, 153, 153));
       remove_btn.setText("Remove Row");
       impute_panel.add(remove_btn);

       center_panel.add(impute_panel);

       outlier_panel.setBackground(new java.awt.Color(34, 40, 44));
       outlier_panel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
       outlier_panel.setPreferredSize(new java.awt.Dimension(210, 600));

       std_btn.setBackground(new java.awt.Color(34, 40, 44));
       std_btn.setForeground(new java.awt.Color(153, 153, 153));
       std_btn.setText("Standard Deviation");
       outlier_panel.add(std_btn);

       std_spinner.setFont(new java.awt.Font("Courier New", 0, 11)); // NOI18N
       outlier_panel.add(std_spinner);

       dbscan_btn.setBackground(new java.awt.Color(34, 40, 44));
       dbscan_btn.setForeground(new java.awt.Color(153, 153, 153));
       dbscan_btn.setSelected(true);
       dbscan_btn.setText("  DBSCAN      ");
       dbscan_btn.setToolTipText("");
       outlier_panel.add(dbscan_btn);

       jSlider1.setBackground(new java.awt.Color(34, 40, 44));
       outlier_panel.add(jSlider1);

       iqr_btn.setBackground(new java.awt.Color(34, 40, 44));
       iqr_btn.setForeground(new java.awt.Color(153, 153, 153));
       iqr_btn.setText("Inter Quartile Range");
       outlier_panel.add(iqr_btn);
       outlier_panel.add(iqr_spinner);

       center_panel.add(outlier_panel);

       scale_panel.setBackground(new java.awt.Color(34, 40, 44));
       scale_panel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
       scale_panel.setPreferredSize(new java.awt.Dimension(210, 600));

       width_btn.setBackground(new java.awt.Color(34, 40, 44));
       width_btn.setForeground(new java.awt.Color(153, 153, 153));
       width_btn.setText("Equal Width Binning");
       scale_panel.add(width_btn);
       scale_panel.add(numBins_spinner);

       jRadioButton12.setBackground(new java.awt.Color(34, 40, 44));
       jRadioButton12.setForeground(new java.awt.Color(153, 153, 153));
       jRadioButton12.setText("Equal frequency Binning");
       scale_panel.add(jRadioButton12);
       scale_panel.add(jSpinner4);

       jRadioButton14.setBackground(new java.awt.Color(34, 40, 44));
       jRadioButton14.setForeground(new java.awt.Color(153, 153, 153));
       jRadioButton14.setText("Scale -1 to 1");
       scale_panel.add(jRadioButton14);

       center_panel.add(scale_panel);

       standardize_panel.setBackground(new java.awt.Color(34, 40, 44));
       standardize_panel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
       standardize_panel.setPreferredSize(new java.awt.Dimension(210, 600));

       standardize_btn.setBackground(new java.awt.Color(34, 40, 44));
       standardize_btn.setForeground(new java.awt.Color(153, 153, 153));
       standardize_btn.setText("Standardize");
       standardize_panel.add(standardize_btn);

       center_panel.add(standardize_panel);

       add(center_panel, java.awt.BorderLayout.CENTER);
   }// </editor-fold>                        


   // Variables declaration - do not modify                     
   private javax.swing.ButtonGroup buttonGroup1;
   private javax.swing.JPanel center_panel;
   private javax.swing.JRadioButton dbscan_btn;
   private javax.swing.JPanel impute_panel;
   private javax.swing.JRadioButton iqr_btn;
   private javax.swing.JSpinner iqr_spinner;
   private javax.swing.JLabel jLabel1;
   private javax.swing.JLabel jLabel2;
   private javax.swing.JLabel jLabel3;
   private javax.swing.JLabel jLabel4;
   private javax.swing.JRadioButton jRadioButton12;
   private javax.swing.JRadioButton jRadioButton14;
   private javax.swing.JSlider jSlider1;
   private javax.swing.JSpinner jSpinner4;
   private javax.swing.JRadioButton mean_btn;
   private javax.swing.JRadioButton median_btn;
   private javax.swing.JRadioButton model_btn;
   private javax.swing.JSpinner numBins_spinner;
   private javax.swing.JPanel outlier_panel;
   private javax.swing.JRadioButton rand_btn;
   private javax.swing.JRadioButton remove_btn;
   private javax.swing.JPanel scale_panel;
   private javax.swing.JRadioButton standardize_btn;
   private javax.swing.JPanel standardize_panel;
   private javax.swing.JRadioButton std_btn;
   private javax.swing.JSpinner std_spinner;
   private javax.swing.JPanel top_panel;
   private javax.swing.JRadioButton width_btn;
   // End of variables declaration                   
}