package logan.sybilGUI;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.plaf.basic.BasicButtonUI;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.io.PrintStream;

import java.awt.*; //new gif

import javax.swing.JLabel;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import java.awt.Image;
import java.awt.Toolkit;
/**
 *
 * @author Owner
 */
public class MainFrame extends javax.swing.JFrame {
	
	private java.awt.Color main_bg_color = new java.awt.Color(34, 40, 44);
	private java.awt.Color main_side_color = new java.awt.Color(22,22,22);
	private java.awt.Color second_side_color = new java.awt.Color(24, 20, 44);
	private int window_width = 1400;
	private int window_height = 1400;
    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        JButton[] buttons = {home_btn,data_btn,stats_btn,preProcess_btn,AI_btn,score_btn,terminal_btn};
        for(final JButton btn : buttons){
            btn.setBackground(main_side_color);
            btn.setUI(new BasicButtonUI());
            btn.addMouseListener(new MouseListener(){

                public void mouseClicked(MouseEvent e) {
                }
                public void mousePressed(MouseEvent e) {
                }
                public void mouseReleased(MouseEvent e) {
                }
                public void mouseEntered(MouseEvent e) {
                    btn.setBackground(new Color(44,44,44));
                }
                public void mouseExited(MouseEvent e) {
                    btn.setBackground(main_side_color);
                }
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {
    	DATA_VIEW = new Data_Panel2(window_width-100,window_height-200,main_bg_color,second_side_color);
    	STATS_VIEW = new Stats_Panel2(window_width-100,window_height-200,main_bg_color,second_side_color);
    	second  = new dummy_secondPanel(window_width-100,window_height-200,main_bg_color,second_side_color);
    	setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    	
    	
    	
        root_panel = new javax.swing.JPanel();
        main_panel = new javax.swing.JPanel();
        side_panel = new javax.swing.JPanel();
        home_btn_panel = new javax.swing.JPanel();
        home_btn = new javax.swing.JButton();
        data_btn = new javax.swing.JButton();
        stats_btn = new javax.swing.JButton();
        preProcess_btn = new javax.swing.JButton();
        AI_btn = new javax.swing.JButton();
        score_btn = new javax.swing.JButton();
        terminal_btn = new javax.swing.JButton();
        open_pjct_btn = new javax.swing.JButton();
        new_project_btn = new javax.swing.JButton();
        
        center_panel = new javax.swing.JPanel();
        top_panel = new javax.swing.JPanel();
        sybilLogo_panel = new javax.swing.JPanel();
        logo_label = new javax.swing.JLabel();
        bottom_panel = new javax.swing.JPanel();

        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        //ROOT PANEL
        root_panel.setPreferredSize(new java.awt.Dimension(window_width, window_height));
        root_panel.setLayout(new java.awt.BorderLayout());

        main_panel.setBackground(main_bg_color);
        main_panel.setPreferredSize(new java.awt.Dimension(window_width-100, window_height - (2*(window_height/10))) );
        main_panel.setLayout(new java.awt.BorderLayout());

        bottom_panel.setBackground(main_bg_color);
        bottom_panel.setPreferredSize(new java.awt.Dimension(window_width-100, 100));
        
        new_project_btn.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        new_project_btn.setBackground(main_bg_color);
        new_project_btn.setIcon(GUI_Util.getIcon("SYBIL_GUI/home_icons/icons8_plus_2_math_50px_2.png",50,50));
        new_project_btn.setText("New Project");
        
        open_pjct_btn.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        open_pjct_btn.setBackground(main_bg_color);
        open_pjct_btn.setForeground(new java.awt.Color(153, 153, 153));
        open_pjct_btn.setIcon(GUI_Util.getIcon("SYBIL_GUI/home_icons/icons8_opened_folder_50px_1.png",50,50)); // NOI18N
        open_pjct_btn.setText("Open Project");
        
        //BOTTOM PANEL
        javax.swing.GroupLayout bottom_panelLayout = new javax.swing.GroupLayout(bottom_panel);
        bottom_panel.setLayout(bottom_panelLayout);
        bottom_panelLayout.setHorizontalGroup(
            bottom_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bottom_panelLayout.createSequentialGroup()
                .addGap(148, 148, 148)
                .addComponent(open_pjct_btn)
                .addGap(57, 57, 57)
                .addComponent(new_project_btn)
                .addContainerGap(597, Short.MAX_VALUE))
        );
        bottom_panelLayout.setVerticalGroup(
            bottom_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bottom_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bottom_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(new_project_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(open_pjct_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        main_panel.add(bottom_panel, java.awt.BorderLayout.SOUTH);
        
        //BOTTOM PANEL
        
        //TOP PANEL
        top_panel.setBackground(main_bg_color);
        top_panel.setPreferredSize(new java.awt.Dimension(window_width-100, 100));
        top_panel.setRequestFocusEnabled(false);
        
        //LOGO
        sybilLogo_panel.setBackground(main_bg_color);
        sybilLogo_panel.setPreferredSize(new java.awt.Dimension(300, 100));

        logo_label.setIcon(GUI_Util.getIcon("SYBIL_GUI/home_icons/sybilLOGO.png",300,100)); // NOI18N
        logo_label.setText("");
        logo_label.setPreferredSize(new java.awt.Dimension(300, 100));
        sybilLogo_panel.add(logo_label);
        
        javax.swing.GroupLayout top_panelLayout = new javax.swing.GroupLayout(top_panel);
        top_panel.setLayout(top_panelLayout);
        top_panelLayout.setHorizontalGroup(
            top_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(top_panelLayout.createSequentialGroup()
                .addComponent(sybilLogo_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 800, Short.MAX_VALUE))
        );
        top_panelLayout.setVerticalGroup(
            top_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, top_panelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(sybilLogo_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        main_panel.add(top_panel, java.awt.BorderLayout.NORTH);
        //TOP PANEL
        
        //CENTER PANEL

        center_panel.setBackground(main_bg_color);
        center_panel.setPreferredSize(new java.awt.Dimension(window_width-100, window_height-200));
        
        
        //center_panel=new Background_Panel_1(center_panel.getWidth(),center_panel.getHeight());
        //center_panel.add(new Background_Panel_1(center_panel.getWidth(),center_panel.getHeight()), java.awt.BorderLayout.CENTER);
        // Set JWindow size from image size
        //setSize(imageIcon.getIconWidth(),imageIcon.getIconHeight());
        //center_panel.add(imageLabel, java.awt.BorderLayout.CENTER);
        
        
        jLabel4.setFont(new java.awt.Font("Courier New", 0, 48)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("Recent Projects");
        jLabel4.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        
        
        main_panel.add(center_panel, java.awt.BorderLayout.CENTER);
        
        //CENTER PANEL
        
        root_panel.add(main_panel, java.awt.BorderLayout.LINE_END);
        
        //SIDE PANEL
        side_panel.setBackground(main_side_color);
        side_panel.setPreferredSize(new java.awt.Dimension(100, window_height));
        
        home_btn_panel.setBackground(main_side_color);
        home_btn_panel.setPreferredSize(new java.awt.Dimension(100, 200));

        home_btn.setBackground(main_side_color);
        home_btn.setIcon(GUI_Util.getIcon("SYBIL_GUI/home_icons/icons8_home_50px_3.png",50,50)); // NOI18N
        home_btn.setPreferredSize(new java.awt.Dimension(50, 50));

        home_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                home_btn_ActionPerformed(evt);
            }
        });
        
        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(home_btn_panel);
        home_btn_panel.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(home_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(home_btn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(87, Short.MAX_VALUE))
        );
        
        side_panel.add(home_btn_panel);

        data_btn.setBackground(main_side_color);
        data_btn.setForeground(new java.awt.Color(255, 255, 255));
        data_btn.setIcon(GUI_Util.getIcon("SYBIL_GUI/home_icons/oct.png",50,50)); // NOI18N
        data_btn.setPreferredSize(new java.awt.Dimension(50, 50));
        data_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                data_btn_ActionPerformed(evt);
            }
        });
        side_panel.add(data_btn);

        stats_btn.setBackground(main_side_color);
        stats_btn.setForeground(new java.awt.Color(255, 255, 255));
        stats_btn.setIcon(GUI_Util.getIcon("SYBIL_GUI/home_icons/icons8_combo_chart_50px_1.png",50,50)); // NOI18N
        stats_btn.setPreferredSize(new java.awt.Dimension(50, 50));
        stats_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stats_btn_ActionPerformed(evt);
            }
        });
        side_panel.add(stats_btn);

        preProcess_btn.setBackground(main_side_color);
        preProcess_btn.setForeground(new java.awt.Color(255, 255, 255));
        preProcess_btn.setIcon(GUI_Util.getIcon("SYBIL_GUI/home_icons/icons8_filter_50px_2.png",50,50)); // NOI18N
        preProcess_btn.setPreferredSize(new java.awt.Dimension(50, 50));
        preProcess_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        side_panel.add(preProcess_btn);

        AI_btn.setBackground(main_side_color);
        AI_btn.setForeground(new java.awt.Color(255, 255, 255));
        AI_btn.setIcon(GUI_Util.getIcon("SYBIL_GUI/home_icons/icons8_artificial_intelligence_50px.png",50,50)); // NOI18N
        AI_btn.setPreferredSize(new java.awt.Dimension(50, 50));
        AI_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        side_panel.add(AI_btn);

        score_btn.setBackground(main_side_color);
        score_btn.setForeground(new java.awt.Color(255, 255, 255));
        score_btn.setIcon(GUI_Util.getIcon("SYBIL_GUI/home_icons/icons8_define_location_50px.png",50,50)); // NOI18N
        score_btn.setPreferredSize(new java.awt.Dimension(50, 50));
        score_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        side_panel.add(score_btn);
        
        terminal_btn.setBackground(main_side_color);
        terminal_btn.setForeground(new java.awt.Color(255, 255, 255));
        terminal_btn.setIcon(GUI_Util.getIcon("SYBIL_GUI/home_icons/icons8_source_code_50px.png",50,50)); // NOI18N
        terminal_btn.setPreferredSize(new java.awt.Dimension(50, 50));
        terminal_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                terminal_btn_ActionPerformed(evt);
            }
        });
        side_panel.add(terminal_btn);
        
        root_panel.add(side_panel, java.awt.BorderLayout.WEST);
        getContentPane().add(root_panel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>                        

    private void data_btn_ActionPerformed(java.awt.event.ActionEvent evt) {                                         
		center_panel.removeAll();
		center_panel.add(DATA_VIEW);
		center_panel.repaint();
		center_panel.revalidate();
    }                                        

    private void stats_btn_ActionPerformed(java.awt.event.ActionEvent evt) {                                         
		center_panel.removeAll();
		center_panel.add(STATS_VIEW);
		center_panel.repaint();
		center_panel.revalidate();
    }                                        

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {                                         
		center_panel.removeAll();
		center_panel.add(second);
		center_panel.repaint();
		center_panel.revalidate();
    }                                        

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    }         
    private void home_btn_ActionPerformed(java.awt.event.ActionEvent evt)  {
			center_panel.removeAll();
			//center_panel.add(data_label_panel);
			center_panel.repaint();
			center_panel.revalidate();
    }
    private void terminal_btn_ActionPerformed(java.awt.event.ActionEvent evt) {
        JFrame frame = new JFrame();
        frame.add( new JLabel(" SYBIL" ), BorderLayout.NORTH );

        JTextArea ta = new JTextArea();
        ta.setBackground(Color.black);
        ta.setForeground(Color.gray);
        TextAreaOutputStream taos = new TextAreaOutputStream( ta, 60 );
        PrintStream ps = new PrintStream( taos );
        System.setOut( ps );
        System.setErr( ps );


        frame.add( new JScrollPane( ta )  );

        frame.pack();
        frame.setVisible( true );
        frame.setSize(800,600);
    }
    
    private ImageIcon getIcon(String File) {
    	BufferedImage icon = null;
		try {
			//File file = new File("icons8_octahedron_50px_1.png")
			icon = ImageIO.read(new File(File));
		} catch (IOException e1) {
			// TODO Auto-generated catch block
			e1.printStackTrace();
		}
		//Add custom icons to passwords
		JLabel picLabel = new JLabel();
		picLabel.setSize(50, 50);
		Image dimg = icon.getScaledInstance(picLabel.getWidth(), picLabel.getHeight(),Image.SCALE_SMOOTH);
		ImageIcon imageIcon = new ImageIcon(dimg);
		return imageIcon;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JPanel bottom_panel;
    private javax.swing.JPanel center_panel;
    private javax.swing.JButton data_btn;
    private javax.swing.JButton stats_btn;
    private javax.swing.JButton preProcess_btn;
    private javax.swing.JButton AI_btn;
    private javax.swing.JButton score_btn;
    private javax.swing.JButton home_btn;
    private javax.swing.JButton terminal_btn;
    private javax.swing.JButton open_pjct_btn;
    private javax.swing.JButton new_project_btn;

    
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel home_btn_panel;
    private javax.swing.JLabel logo_label;
    private javax.swing.JPanel root_panel;
    private javax.swing.JPanel side_panel;
    private javax.swing.JPanel sybilLogo_panel;
    private javax.swing.JPanel top_panel;
    private javax.swing.JPanel main_panel;
    
    private javax.swing.JPanel second;
    // End of variables declaration
    //OTHER VIEWS
    private javax.swing.JPanel DATA_VIEW;
    private javax.swing.JPanel STATS_VIEW;
}
