package logan.sybilGUI;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import javax.swing.JLabel;

import Controllers.Data_Label_Controller;

public class Stats_Panel extends Secondary_View{

	private int btn_size = 50;
	Data_Label_Controller ctrl;
	
	public Stats_Panel(int width, int height, Color main_bg_color, Color main_side_color,Data_Label_Controller ctrl) {
		super(width, height, main_bg_color, main_side_color);
		this.ctrl = ctrl;
	}
	/**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    protected void initComponents() {
    	
        hypo_test_btn = new javax.swing.JButton();
        scatter_plt_btn = new javax.swing.JButton();
        regression = new javax.swing.JButton();
        distribution = new javax.swing.JButton();
        area_compare_btn = new javax.swing.JButton();
        bar_chart_btn = new javax.swing.JButton();
        box_plot_btn = new javax.swing.JButton();
        pie_chart_btn = new javax.swing.JButton();

        //HYPO_VIEW = new Hypothesis_Panel(center_panel.getWidth(),center_panel.getHeight(),main_bg_color,main_side_color);
        HYPO_VIEW = new Hypothesis_Panel(center_panel.getPreferredSize().width,center_panel.getPreferredSize().height,main_bg_color,main_side_color,200);
        
        
        int btn_size = 50;
        hypo_test_btn.setBackground(main_side_color);
        hypo_test_btn.setIcon(GUI_Util.getIcon("SYBIL_GUI/stats_icons/icons8_Millenium_Eye_50px_1.png",btn_size,btn_size)); // NOI18N
        hypo_test_btn.setToolTipText("all seeing eye");
        
        hypo_test_btn.addActionListener(new ActionListener() {
         	public void actionPerformed(ActionEvent e) {
      			testAction(e);
         	}
      });

        side_panel.add(hypo_test_btn);

        scatter_plt_btn.setBackground(main_side_color);
        scatter_plt_btn.setIcon(GUI_Util.getIcon("SYBIL_GUI/stats_icons/icons8_scatter_plot_50px.png",btn_size,btn_size)); // NOI18N // NOI18N 
        scatter_plt_btn.setToolTipText("scatter");
        scatter_plt_btn.addActionListener(new ActionListener() {
         	public void actionPerformed(ActionEvent e) {
         		scatter_2D_Action(e);
         	}
      });
        side_panel.add(scatter_plt_btn);

        regression.setBackground(main_side_color);
        regression.setIcon(GUI_Util.getIcon("SYBIL_GUI/stats_icons/icons8_coordinate_system_50px.png",btn_size,btn_size)); // NOI18N
        regression.setToolTipText("regression");
        regression.addActionListener(new ActionListener() {
         	public void actionPerformed(ActionEvent e) {
         		regressionAction(e);
         	}
      });
        side_panel.add(regression);

        distribution.setBackground(main_side_color);
        distribution.setIcon(GUI_Util.getIcon("SYBIL_GUI/stats_icons/icons8_normal_distribution_histogram_50px.png",btn_size,btn_size)); // NOI18N
        side_panel.add(distribution);

        area_compare_btn.setBackground(main_side_color);
        area_compare_btn.setIcon(GUI_Util.getIcon("SYBIL_GUI/stats_icons/icons8_area_chart_filled_50px.png",btn_size,btn_size)); // NOI18N
        side_panel.add(area_compare_btn);

        bar_chart_btn.setBackground(main_side_color);
        bar_chart_btn.setIcon(GUI_Util.getIcon("SYBIL_GUI/stats_icons/icons8_bar_chart_50px_1.png",btn_size,btn_size)); // NOI18N
        side_panel.add(bar_chart_btn);

        box_plot_btn.setBackground(main_side_color);
        box_plot_btn.setIcon(GUI_Util.getIcon("SYBIL_GUI/stats_icons/icons8_candle_sticks_filled_50px.png",btn_size,btn_size)); // NOI18N
        side_panel.add(box_plot_btn);

        pie_chart_btn.setBackground(main_side_color);
        pie_chart_btn.setIcon(GUI_Util.getIcon("SYBIL_GUI/stats_icons/icons8_doughnut_chart_filled_50px.png",btn_size,btn_size)); // NOI18N
        side_panel.add(pie_chart_btn);
        
        add(side_panel, java.awt.BorderLayout.WEST);
        
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(side_panel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(center_panel, javax.swing.GroupLayout.DEFAULT_SIZE, W, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(side_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(center_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        add(center_panel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>     
    
    private void testAction(java.awt.event.ActionEvent evt) {
		center_panel.removeAll();
		center_panel.add(HYPO_VIEW);
		center_panel.repaint();
		center_panel.revalidate();
    }
    private void regressionAction(java.awt.event.ActionEvent evt) {
    	REG_3D_VIEW = new ThreeD_Scatter_Panel(center_panel.getPreferredSize().width,center_panel.getPreferredSize().height,main_bg_color,main_side_color,200,ctrl);
		center_panel.removeAll();
		center_panel.add(REG_3D_VIEW);
		center_panel.repaint();
		center_panel.revalidate();
    }
    private void scatter_2D_Action(java.awt.event.ActionEvent evt) {
    	SCATTER_2D_VIEW = new TwoD_Scatter_Panel2(center_panel.getPreferredSize().width,center_panel.getPreferredSize().height,main_bg_color,main_side_color,200,ctrl);
    	System.out.println("@DDDDDDDD");
		center_panel.removeAll();
		center_panel.add(SCATTER_2D_VIEW);
		center_panel.repaint();
		center_panel.revalidate();
    }
    // Variables declaration - do not modify                     
    private javax.swing.JButton area_compare_btn;
    private javax.swing.JButton distribution;
    private javax.swing.JButton bar_chart_btn;
    private javax.swing.JButton box_plot_btn;
    private javax.swing.JButton pie_chart_btn;
    private javax.swing.JButton regression;
    private javax.swing.JButton scatter_plt_btn;
    private javax.swing.JButton hypo_test_btn;
    // End of variables declaration 
    //VIEWS
    private javax.swing.JPanel HYPO_VIEW;
    private javax.swing.JPanel REG_3D_VIEW;
    private javax.swing.JPanel SCATTER_2D_VIEW;
}
