package logan.sybilGUI;

import java.awt.Color;

import javax.swing.JLabel;

public class Stats_Panel2 extends Secondary_View{

	private int btn_size = 50;
	
	public Stats_Panel2(int width, int height, Color main_bg_color, Color main_side_color) {
		super(width, height, main_bg_color, main_side_color);
	}
	/**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    protected void initComponents() {
    	
        hypo_test_btn = new javax.swing.JButton();
        scatter_plt_btn = new javax.swing.JButton();
        regression = new javax.swing.JButton();
        distribution = new javax.swing.JButton();
        area_compare_btn = new javax.swing.JButton();
        bar_chart_btn = new javax.swing.JButton();
        box_plot_btn = new javax.swing.JButton();
        pie_chart_btn = new javax.swing.JButton();

        int btn_size = 50;
        hypo_test_btn.setBackground(main_side_color);
        hypo_test_btn.setIcon(GUI_Util.getIcon("SYBIL_GUI/stats_icons/icons8_Millenium_Eye_50px_1.png",btn_size,btn_size)); // NOI18N
        hypo_test_btn.setToolTipText("all seeing eye");
        
        hypo_test_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                testAction(evt);
            }
        });

        side_panel.add(hypo_test_btn);

        scatter_plt_btn.setBackground(main_side_color);
        scatter_plt_btn.setIcon(GUI_Util.getIcon("SYBIL_GUI/stats_icons/icons8_scatter_plot_50px.png",btn_size,btn_size)); // NOI18N // NOI18N 
        scatter_plt_btn.setToolTipText("scatter");
        side_panel.add(scatter_plt_btn);

        regression.setBackground(main_side_color);
        regression.setIcon(GUI_Util.getIcon("SYBIL_GUI/stats_icons/icons8_coordinate_system_50px.png",btn_size,btn_size)); // NOI18N
        regression.setToolTipText("regression");
        side_panel.add(regression);

        distribution.setBackground(main_side_color);
        distribution.setIcon(GUI_Util.getIcon("SYBIL_GUI/stats_icons/icons8_normal_distribution_histogram_50px.png",btn_size,btn_size)); // NOI18N
        side_panel.add(distribution);

        area_compare_btn.setBackground(main_side_color);
        area_compare_btn.setIcon(GUI_Util.getIcon("SYBIL_GUI/stats_icons/icons8_area_chart_filled_50px.png",btn_size,btn_size)); // NOI18N
        side_panel.add(area_compare_btn);

        bar_chart_btn.setBackground(main_side_color);
        bar_chart_btn.setIcon(GUI_Util.getIcon("SYBIL_GUI/stats_icons/icons8_bar_chart_50px_1.png",btn_size,btn_size)); // NOI18N
        side_panel.add(bar_chart_btn);

        box_plot_btn.setBackground(main_side_color);
        box_plot_btn.setIcon(GUI_Util.getIcon("SYBIL_GUI/stats_icons/icons8_candle_sticks_filled_50px.png",btn_size,btn_size)); // NOI18N
        side_panel.add(box_plot_btn);

        pie_chart_btn.setBackground(main_side_color);
        pie_chart_btn.setIcon(GUI_Util.getIcon("SYBIL_GUI/stats_icons/icons8_doughnut_chart_filled_50px.png",btn_size,btn_size)); // NOI18N
        side_panel.add(pie_chart_btn);
        
        add(side_panel, java.awt.BorderLayout.WEST);
        
        center_panel.setBackground(Color.GREEN);
        center_panel.setPreferredSize(new java.awt.Dimension(W, H));
        
        HYPO_VIEW = new Hypothesis_Panel(center_panel.getWidth(),center_panel.getHeight(),main_bg_color,main_side_color);
        System.out.println(HYPO_VIEW.getHeight());
        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(center_panel);

        
        center_panel.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        
        
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(side_panel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(center_panel, javax.swing.GroupLayout.DEFAULT_SIZE, W, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(side_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(center_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        add(center_panel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>     
    
    private void testAction(java.awt.event.ActionEvent evt) {
		center_panel.removeAll();
		center_panel.add(HYPO_VIEW);
		center_panel.repaint();
		center_panel.revalidate();
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton area_compare_btn;
    private javax.swing.JButton distribution;
    private javax.swing.JButton bar_chart_btn;
    private javax.swing.JButton box_plot_btn;
    private javax.swing.JButton pie_chart_btn;
    private javax.swing.JButton regression;
    private javax.swing.JButton scatter_plt_btn;
    private javax.swing.JButton hypo_test_btn;
    // End of variables declaration 
    //VIEWS
    private javax.swing.JPanel HYPO_VIEW;
}
